-- USER SQL
CREATE USER HEALTH IDENTIFIED BY "1234"  
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER HEALTH QUOTA 10M ON USERS;

-- ROLES
GRANT "CONNECT" TO HEALTH ;
GRANT "RESOURCE" TO HEALTH ;

-- SYSTEM PRIVILEGES

