DROP SEQUENCE RECEIPT_T_SEQ;
DROP TABLE RECEIPT_T;

DROP SEQUENCE STAFF_T_SEQ;
DROP TABLE STAFF_T;

DROP SEQUENCE REPAIR_ITEM_T_SEQ;
DROP TABLE REPAIR_ITEM_T;

DROP SEQUENCE CUSTOMER_T_SEQ;
DROP TABLE CUSTOMER_T;

DROP SEQUENCE CAR_T_SEQ;
DROP TABLE CAR_T;
